filters:
  - name: f_azure
    condition: |-
      tag('vendor:microsoft') and tag('product:azure');

logPaths:
  - name: path1
    filters:
      - filter(f_azure)
    template: t_logscale_parsed
    tags:
      - name: "Vendor"
        value: microsoft
      - name: "type"
        value: "micrososft-azure-ad"
      - name: "repo"
        value: "micrososft-azure-ad"

    flags: [catchall]
  - name: fallback
    tags:
      - name: "Vendor"
        value: unknown
      - name: "type"
        value: "segway-fallback"
      - name: "repo"
        value: "segway-fallback"
    flags: [fallback]
