filters:
  - name: f_azure
    condition: |-
      tag('vendor:microsoft') and tag('product:azure');

logPaths:
  - name: path1
    filters:
      - filter(f_azure)
    template: t_logscale_parsed
    repo: micrososft-azure-ad
    tags:
      - name: "Vendor"
        value: microsoft
    type: "micrososft-azure-ad"
    flags: [catchall]
  - name: fallback
    repo: segway-fallback
    flags: [fallback]
